
language: cpp
compiler: gcc
os: linux

install:
  - git clone --branch=master https://github.com/izuzanak/cont.git ~/build/izuzanak/cont

  - cd ~/build/izuzanak/cont/build
  - cmake ..
  - make

script:
  - cd ~/build/izuzanak/cont_c/build
  - cmake ..
  - make

  - cd ~/build/izuzanak/cont/build
  - sudo make install

  - cd ~/build/izuzanak/cont_c/build
  - rm -rf *
  - cmake ..
  - make

