
language: cpp
compiler: gcc
os: linux
git:
  clone: false

install:
  - git clone --branch=master https://github.com/izuzanak/cont.git cont
  - git clone --branch=cont_c https://github.com/izuzanak/cont.git cont_c

  - cd ~/build/cont/build
  - cmake ..
  - make
  - sudo make install

script:
  - cd ~/build/cont_c/build
  - cmake ..
  - make

