
language: cpp
compiler: gcc
os: linux

script:
  - cd ~/build/izuzanak/cont/build
  - cmake ..
  - make
  - sudo make install

  - rm -rf *
  - cmake ..
  - make
  - sudo make install

  - cd ~/build/izuzanak/cont/cont
  - ./test.sh

